### ISSUE TITLE
How do I return the "value" of selected choices instead of "name"?

### ISSUE THREAD

**Issue by 3cp** [enquirer/enquirer#121]
```js
prompt([{
  type: 'select',
  name: 'fruit',
  message: 'Favorite fruit?',
  choices: [
    { name: 'Apple', message: 'Apple', value: 'app' },
    { name: 'Orange', message: 'Orange', value: 'ora' },
    { name: 'Raspberry', message: 'Raspberry', value: 'res' }
  ]
}]).then(answers => console.log(answers));
```
It prints `{fruit: 'Apple'}` instead of `{fruit: 'app'}`.

**Comment by rgilbert1** [comment]
After digging around the codebase for a while, I located the [line of code](https://github.com/enquirer/enquirer/blob/master/lib/types/array.js#L555) that would need to change to fix (at least this) case.

It's currently:
```javascript
this.value = multi ? value.map(ch => ch.name) : value.name;
```

Changing it to:
```javascript
this.value = multi ? value.map(ch => ch.value ? ch.value : ch.name) : value.value ? value.value : value.name;
```
(or something cleaner) would give us the functionality we're looking for. I'm not sure if this is intended functionality anymore, but it would be nice to have something like it 😄

**Comment by rgilbert1** [comment]
I found a workaround that wouldn't require a code change in this codebase. I was looking at [this test](https://github.com/enquirer/enquirer/blob/master/test/prompt.multiselect.js#L56) and noticed the `result` function that gets passed in. Using that, we can actually pull the `value` field out ourselves, like this:

```javascript
prompt([{
  type: 'select',
  name: 'fruit',
  message: 'Favorite fruit?',
  choices: [
    { name: 'Apple', message: 'Apple', value: 'app' },
    { name: 'Orange', message: 'Orange', value: 'ora' },
    { name: 'Raspberry', message: 'Raspberry', value: 'res' }
  ],
  result(choice) {
    return this.map(choice)[choice];
  }  
}]).then(answers => console.log(answers));
```

This produces expected behavior :tada:

**Comment by jonschlinkert** [comment]
> This produces expected behavior

@rgilbert1 thank you for adding the example! 

FWIW, the reason `name` is returned is that it allows you to easily the value and/or any other property you want from the selected choice(s). 

Since @rgilbert1's example shows how to return an object with key-value pairs, where the key is the `choice.name`, and value is the `choice.value`, if you'd rather have an array of values as the result, you can do something like this:

```js
const questions = {
  type: 'multiselect',
  name: 'example',
  message: 'Take your pick',
  choices: [
    { name: 'foo', value: true },
    { name: 'bar', value: false },
    { name: 'baz', value: 42 }
  ],
  result(names) {
    return names.map(name => this.find(name).value);
  }
};

enquirer.prompt([questions])
  .then(console.log)
  .catch(console.error);
```

**Comment by MikeZyeman** [comment]
@jonschlinkert Unfortunately this does work when there are only choices with unique names.

I'll take your previous code as an example:

```
const questions = {
  type: 'multiselect',
  name: 'example',
  message: 'Take your pick',
  choices: [
    { name: 'foo', value: true },
    { name: 'bar', value: false },
    { name: 'baz', value: 42 },
    { name: 'baz', value: true }
  ],
  result(names) {
    return names.map(name => this.find(name).value);
  }
};

enquirer.prompt([questions])
  .then(console.log)
  .catch(console.error);
```
As you can see, there are two choices with the name 'baz'. The first 'baz' has the value of **42** and the second has the value of **true**

If you select the first 'baz', when you get the expected value of **42**, but if you select the second 'baz', you will get **42** instead of **true**.

You have to add message, when you want to display a choice with the same name.

```
const questions = {
  type: 'multiselect',
  name: 'example',
  message: 'Take your pick',
  choices: [
    { name: 'foo', message: 'foo', value: true },
    { name: 'bar', message: 'bar', value: false },
    { name: 'baz', message: 'baz', value: 42 },
    { name: 'baz2', message: 'baz', value: true }
  ],
  result(names) {
    return names.map(name => this.find(name).value);
  }
};

enquirer.prompt([questions])
  .then(console.log)
  .catch(console.error);
```

**Comment by nikolay-borzov** [comment]
Returning `name` values instead of `value` values is confusing. If it's by design - this design contradicts common expectations

**Comment by jonschlinkert** [comment]
> If you select the first 'baz', when you get the expected value of **42**, but if you select the second 'baz', you will get **42** instead of **true**.

@MikeZyeman `name` is the unique ID for choices. Seems like it would be more effective to use a different property to define those duplicate values.

***

> Returning `name` values instead of `value` values is confusing. If it's by design - this design contradicts common expectations

Really? You know what common expectations are? I think that you should be getting paid $1b/year, if you're able to understand everyone in the world's expectations without actually doing any research or seeing data. That's amazing. Truly!

/end sarcasm

Returning `value` makes no sense at all. Choices can have any custom properties you want, and many users need other properties besides `value`. You can make choices [Dirents](https://nodejs.org/api/fs.html#fs_class_fs_dirent), in which case you might need the `name` property. Or you can define  `path`, and then you'll want that property. 

It seems, as is common in programming, that you are assuming that your very limited use case represents what everyone else does, when in fact your opinion might not even represent the majority.

**Comment by nikolay-borzov** [comment]
Common expectations are
- name is not unique and used to represent text to a user
- value is unique and used to identify the item

> Choices can have any custom properties you want, and many users need other properties besides value.

Then why not return choice objects itself instead of just `name` values?

**Comment by Cellule** [comment]
I was personally very confused by that and by looking at the doc in the README, I was fully expecting to get the `value` as the result of the prompt since a value is something you use in your code, a name is a way to refer to that value. 
![image](https://user-images.githubusercontent.com/4157103/72126983-11541980-333c-11ea-8ea4-e292ea88e15c.png)
With the current behavior it's really convoluted to get the value back. The easiest solution I can think of is to make a map myself and don't even bother passing a value to the prompt since it won't be returned back to me.

**Comment by jonschlinkert** [comment]
@Cellule, @nikolay-borzov, 

- what if `{ multiple: true }` is enabled? 
- what if `value` is not unique? Since it doesn't have to be. 

`name` is synonymous with `key`, but every choice could have the same value, like `pepperoni` => `true`, `extra_cheese` => `true`. You are saying that you just want a single `true` value? Or do you want an array? `[true, true]`? 

Or are you arguing that since you don't use it that way, that no one else does either? Or that it's unlikely that others use it differently than you? Or that I should not give our users the flexibility to get choices back however they want?

**Comment by Cellule** [comment]
Ideally more flexibility the better.
I'm saying that the expectations of the api and from the documentation was that we'd receive the selected "value" from the user's choice.

The problem I have with saying the `name` is a key, a key to what ? I fail to see why I'm giving the value to `prompt` in the first place since I'll have to use the key to map the value myself.

I ended up doing something like the following
```js
const keyValue = {
  key1: {value: "value1", message: "message1"},
  key2: {value: "value2", message: "message2"},
}
const {key} = await prompt({
  type: "autocomplete",
  name: "key",
  message: "question?",
  choices: Object.keys(keyValue).map(key => ({
    name: key,
    message: keyValue[key].message,
    // not passing value here cause not sure what's the point
  }))
});
console.log(`Value chosen: ${keyValue[key].value}`);
```

Also per the documentation, if `value` is missing it says it returns `name` instead. So if your use-case is to receive `name` (aka your key` from the result of the call, that use-case is supported by design.
However, if `value` is specified, it means I want `value` to be returned from the selected choice.

> what if { multiple: true } is enabled?

I admit I am still farily new using `enquirer` and I haven't tried `multi` yet since I haven't had the need, but I would assume it just returns an array of the selected values (or names), no ?

**Comment by doowb** [comment]
In most of the places in the README that mention a `name` it's also referred to as a `key`. In this case, you even posted a screenshot of the [choice properties](https://github.com/enquirer/enquirer#choice-properties) that says that name is `The unique key to identify a choice`.

Also, the comment about `value` is saying that if a `value` is not on the choice properties, then `name` is used. There's an example of how choices are normalized just above the choice properties table. I haven't found any place where it says that the `value` of a `choice` will be returned. (There's also a gif of the `Multiselect` Prompt that has a list of choices with `name` and `value` and the names are returned).

I think this makes sense mainly due to the fact that it's more likely that a value will be duplicated than a name, as seen by Jon's pizza example.

Since this is just JavaScript, you can write your code however you'd like, but as the examples soon in this issue, we have some methods that help return other properties so you don't have to do the `keyValue` thing. You can use the `result` option with the `.map` method like this:

```js
const { prompt } = require('enquirer');

(async() => {
  const choices = [
    { name: 'key1', value: 'value1', message: 'message1' },
    { name: 'key2', value: 'value2', message: 'message2' },
  ];

  const { key } = await prompt({
    type: 'select',
    name: 'key',
    message: 'question?',
    choices,
    result(name) {
      return this.map(name)[name];
    }
  });

  console.log(key);
})();
```

**Comment by jonschlinkert** [comment]
You keep saying “choice”, but the user can optionally have multiple choices.

**Comment by vibl** [comment]
I have read this thread and I'm still not sure if `value` or `name` is supposed to be returned...

From what I've read, I'm guessing it's `name`. If it's the case, whoever wrote this official example was not aware of it: https://github.com/enquirer/enquirer/blob/master/examples/select/option-symbols.js

In the example, the `name` that was selected is just returned, and the `values` are never shown to the user.

**Comment by vibl** [comment]
And this is very strange: in the same example (https://github.com/enquirer/enquirer/blob/master/examples/select/option-symbols.js), if I change `new Select` to `new AutoComplete`, now it's the value that is returned!

There's clearly an incoherence here.

**Comment by jakobrosenberg** [comment]
It's common to have a public title and an internal key. When you provide `name` and `value` in your example, I expect one is external and one is internal.

Speaking of expectations and conventions.
```html
<label for="colors">Choose a color:</label>

<select name="colors" id="colors">
  <option value="#00ffff">aqua</option>
  <option value="#000000">black</option>
  <option value="#0000ff">blue</option>
  <option value="#ff00ff">fuchsia</option>
</select>
```

**Comment by KernelDeimos** [comment]
The problem here is a separation of concerns is not possible.

Ideally, there should be three parameters:
- `name`: a unique identifier. I've seen other libraries and frameworks use `name` instead of `id` so this seems fine.
- `value`: a value. Doesn't have to be unique.
- `label`: alternate text to present to the user. Doesn't have to be unique.

Using the label as a key is the problem. It requires an additional lookup, and it's prone to collisions if the labels you want to present to the user come from some other source that you don't have control over.

**Comment by DASPRiD** [comment]
I ended up using `name` as the value being returned and `message` as what is being displayed. Works like a charm, no other properties required.

**Comment by JohnMunsch** [comment]
If it works as designed, great. If it needs changes, that's great too. What *isn't* great is that the documentation doesn't really address this elephant in the room. Somewhere around where options are defined, it needs to be made super clear how this should be handled and if people need to do a mapping, what they should do. Two paragraphs would fix this for people, like me, who ended up spending 30-90 minutes fighting this and not getting what was expected.
