### ISSUE TITLE
scale prompt example

### ISSUE THREAD

**Issue by 318097** [enquirer/enquirer#143]
## scale
- [ ] prompt.js => having the scale range starting from 1 would be better

**Comment by doowb** [comment]
@318097 I was starting to type something else out, but then realized that the [scale/options-number.js](https://github.com/enquirer/enquirer/blob/bba44f29be3abf7b25acc8a8101bdd7892bb66a5/examples/scale/option-number.js#L7-L13) example shows exactly how to do what I was about to suggest showing.

It does this by passing a `number` method to the `options` that does the work of choosing the correct `scale` choose.

I'm going to close this since I think the `scale/prompt.js` example is good to show the default behavior and the other examples show how options can be used to provide the behavior an implementer chooses.
