### ISSUE TITLE
multi-select: change color based on if selected

### ISSUE THREAD

**Issue by shdblowers** [enquirer/enquirer#176]
Hi, thanks for the library! Finding it very useful.

Wondering, if its possible to, for example, display a choice as green when selected and white when not selected.

Something like this:

![image](https://user-images.githubusercontent.com/11884841/60680468-5bd37580-9e83-11e9-953a-650219efca1a.png)

**Comment by shdblowers** [comment]
Looking to make the selection more obvious across the entire row, as I am displaying a table of data.

**Comment by jonschlinkert** [comment]
Sorry it has taken so long to reply! @doowb and I have been off for a few days. This is definitely doable, I'll post an example ASAP

**Comment by shdblowers** [comment]
forgot it was the holidays in the US 😄 🇺🇸

**Comment by shdblowers** [comment]
I have finished development on my CLI app. No longer required.

**Comment by doowb** [comment]
Lol... so I didn't notice the PR adding an example for this was linked to this issue until the issue was auto-closed.

Thanks to @adityavyas611 there's an example showing how to use `choiceMessage` to change the message styles based on if the choice is selected or not. You can see the [example here](https://github.com/enquirer/enquirer/blob/169b527bb9aec2ffacead9bd6e8ff46cce821662/examples/select/option-select-color.js).
