### ISSUE TITLE
Dynamic menu

### ISSUE THREAD

**Issue by atmoner** [enquirer/enquirer#260]
I have a question, is it possible to create a dynamic menu from a signal with socket?
I would like that at each socket connection (which contains a username and an id), a new menu line be created, is it possible?

```
if (argv.port) {
	
	var io = require("socket.io");
	var sockets = io.listen(argv.port);
 	console.log("Server run on port: "+argv.port);

	sockets.on('connection', function (socket) {
		console.log('Client connected'); 
	});
}
```

**Comment by doowb** [comment]
Yes, it is possible. How you implement it depends on how you want a user to interact with your application and how the "menu" can access the socket connections.

The `choices` option can be a `function` that returns an `Array` of choices, or even a `Promise` that resolves to an `Array` of choices. This means that you can use that to get the current list of connections and dynamically normalize the socket connect objects to a choice object. Or you can simply have a `createMenu` function that creates a new `SelectPrompt` instance and use that when you need to:

```js
const createMenu = connections => {
  return new SelectPrompt({
    name: 'user',
    choices: connections.map(connection => {
      return { name: connection.id, message: connection.username };
    })
  });
};

const menu = createMenu(connections);
const user = await menu.run();
```

I'm going to close this since it's a question, but feel free to add more information here if you'd like.

**Comment by atmoner** [comment]
Hi @doowb and thank you for your reply!
Indeed it is a good solution, so I try to adapt it to use with socket.io
I succeeded but it did not make the result I wanted! Indeed, I use inquire when opening a socket so it opens a whole menu with each new connection!!  
I am now looking for a way to add only one line in the menu at each connection, is it possible to modify the content of the class `AutoComplete()`

![atmo@atmo: ~_202](https://user-images.githubusercontent.com/1071490/73787530-ca6f0d80-479b-11ea-879c-77386170a309.png)

Here is my source:

```js
	var io = require("socket.io");
	var sockets = io.listen(argv.port);
 	console.log("Server run on port: "+argv.port);

	sockets.on('connection', function (socket) {
		console.log('Client connected'); 
		const { AutoComplete } = require('enquirer');
 
		socket.on('sendConnect', function (data) {
		//console.log(data.name);
		var connections = '{'
			   +'"name" : "'+data.name+'",'
			   +'"socket" : "'+socket.id+'"'
			   +'}';

		const parseJsonAsyncFunc = jsonString => {
		  return new Promise(resolve => {
			setTimeout(() => {
			  resolve(JSON.parse(jsonString));
			});
		  });
		}
		 
		const createMenu = connections => {
		  return new AutoComplete({
			name: 'user',
			choices: parseJsonAsyncFunc(connections).then(connection => {
			  return [{ name: connection.socket }];
			})
		  });
		};		

		const menu = createMenu(connections); 			 
		menu.run()
		  .then(answer => console.log('Answer:', answer))
		  .catch(console.error);
		});
	});
```

**Comment by atmoner** [comment]
Hi @doowb and thank you for your reply!
Indeed it is a good solution, so I try to adapt it to use with socket.io
I succeeded but it did not make the result I wanted! Indeed, I use inquire when opening a socket so it opens a whole menu with each new connection!!
I am now looking for a way to add only one line in the menu at each connection, is it possible to modify the content of the class AutoComplete()
 
Here is my source:

```js
	var io = require("socket.io");
	var sockets = io.listen(argv.port);
 	console.log("Server run on port: "+argv.port);

	sockets.on('connection', function (socket) {
		console.log('Client connected'); 
		const { AutoComplete } = require('enquirer');
 
		socket.on('sendConnect', function (data) {
		//console.log(data.name);
		var connections = '{'
			   +'"name" : "'+data.name+'",'
			   +'"socket" : "'+socket.id+'"'
			   +'}';

		const parseJsonAsyncFunc = jsonString => {
		  return new Promise(resolve => {
			setTimeout(() => {
			  resolve(JSON.parse(jsonString));
			});
		  });
		}
		 
		const createMenu = connections => {
		  return new AutoComplete({
			name: 'user',
			choices: parseJsonAsyncFunc(connections).then(connection => {
			  return [{ name: connection.socket }];
			})
		  });
		};		

		const menu = createMenu(connections); 			 
		menu.run()
		  .then(answer => console.log('Answer:', answer))
		  .catch(console.error);
		});
	});
```

**EDIT**
I think I will have to work outside of socket connections!
I would have to create a function which would create a menu and which would be fed by the connection of a new user (in `sockets.on('connection')` ), 

So the good question is:
How to modify the enquirer class already lacing?

**Comment by doowb** [comment]
Take a look at [this example](https://github.com/enquirer/enquirer/blob/d082c0c7222d111e62a780cb988dc7fa9bf174b9/examples/autocomplete/option-suggest-streaming.js#L21-L35). The example is simulating "streaming" data, but this is similar to your case because when a new user connects, it's like new data from the stream. The part that I linked to adds the new data to a list of items, then it converts the items to choices using the `.toChoices` method and adds the choices to the prompt. At the end, the `.render()` method is called, which causes the prompt to update what's shown in the terminal with the newly added choices.

It's a complicated example, but I think the key point is that something updates the list of choices, then calls the `.render()` method. In your case, I think you're correct that the prompt should be created outside of the new socket connections. When a new user connects, update the list of choices and call the prompt instance's `.render()` method.

**Comment by atmoner** [comment]
Really very interesting! Your example allowed me to better understand how to investigate works.
The problem I encounter is for the use of await with socket (it is not compatible, I would have to rewrite it with try / caught)
Finally, it will be easier for me to create a main menu with a simple return of a connection test.

I have another rather simple question, how can I keep the prompt open after an action?
