### ISSUE TITLE
Confirm prompt shows both "Y/n" and boolean

### ISSUE THREAD

**Issue by jpmedley** [enquirer/enquirer#288]
The Confirm prompt requests either "Y" or "n", yet shows a boolean value as the suggested default. It would be nice if the prompt showed only one idiom or even let developers control which idiom to use.

![image](https://user-images.githubusercontent.com/8204171/83673029-14ba9c80-a58c-11ea-99ca-59ad08fc7cad.png)

**Comment by doowb** [comment]
> even let developers control which idiom to use.

This is currently possible because of how flexible Enquirer is.

See [this example](https://github.com/enquirer/enquirer/blob/65f0726b5317e6c0177f8157eb9efd3d134ed405/examples/confirm/option-styles.js#L13) showing how to remove the `true` from showing.

You could also `format` it differently by passing a `format` option like this:

```js
format(value) {
  return this.isTrue(value) ? 'yes' : 'no';
}
```

**Comment by jpmedley** [comment]
Terrific! Thank you.
