### ISSUE TITLE
Space between questions

### ISSUE THREAD

**Issue by mikeerickson** [enquirer/enquirer#292]
I am using `enquirer` to ask a series of questions and would like to have a newline `\n` between each questions to give it is some visual spacing?

I create an array of questions, then pass this array to `prompt` method.  

Is this possible?

**Comment by doowb** [comment]
At the moment, the only way I can think about doing this is to add a `console.log()` after each prompt. If you are calling them manually, then you could do it after the results are returned.

Since you're passing an array of questions to the `prompt` method, you can do this:

```js
const { prompt } = require('enquirer');

prompt.on('submit', () => {
  console.log();
});

prompt(require('./questions'))
  .then(answers => console.log('ANSWERS:', answers))
  .catch(console.error);
```

This will be easier to control through options (the `question` objects) in the next version.

**Comment by mikeerickson** [comment]
@doowb Perfect, does just as I need!  

Thx :-)
