### ISSUE TITLE
Interesting, but annoying docs

### ISSUE THREAD

**Issue by kokujin** [enquirer/enquirer#3]
I was interested, especially when I read it only takes 11ms to load. I decided to try it out by copying and pasting code from the docs:

``````
var enquirer = require('enquirer');

enquirer.question('first', 'First name?');
enquirer.question('last', 'Last name?');

enquirer.ask('first')
  .then(function(answers) {
    console.log(answers);
  });

``````
But no! How dare I! I get this:

``````
enquirer.question('first', 'First name?');
         ^
TypeError: enquirer.question is not a function
``````
I would'nt have bothered actually, I could read the docs further or take a look at the tests to see whats going on, but I have been trying to get my custom generators working using https://github.com/generate/generate, same devs, same problems, documented examples that don't work and one has no idea why.

I apologize.

Does anyone know what I am doing wrong? A code example would be nice. Thanks

**Comment by kokujin** [comment]
Whoa! No code example, or explanation?

**Comment by jonschlinkert** [comment]
Read the attached commit. Read the code. Or, be kind, and you will get help.

**Comment by kokujin** [comment]
I apologized, I thought that was evident. On the other hand, I hinted at something which others might be experiencing.

Could you point out what I am doing wrong in my code snippet?

**Comment by jonschlinkert** [comment]
Not to keep this going, but when you apologize in the same textbox in which you're insulting the developers/maintainers of a project (or even two projects), it hard to take as a sincere comment. Perhaps, instead of apologizing, just revise the comment next time? Just a thought...

While I do appreciate getting issues about mistakes in the docs, I try to keep as positive of an attitude as possible, so I was about to close and lock the issue just because of the antagonistic title. 

Instead, the issue was closed automatically by a code commit that resolved the issue. I fixed the problematic docs. 

You need to instantiate `Enquirer`:

```js
var Enquirer = require('enquirer');
var enquirer = new Enquirer();

enquirer.question('first', 'First name?');
enquirer.question('last', 'Last name?');

enquirer.ask('first')
  .then(function(answers) {
    console.log(answers)
  });

// errors
enquirer.ask('first')
  .then(function(answers) {
    console.log(answers)
  })
  .catch(function(err) {
    console.log(err)
  });
```

Also, regarding your comments about generate, you created an issue there about running locally installed generators without installing generate globally. I commented on that issue, we're working on it. and while I do think that feature should be supported, it's not something that was prioritized or even thought about before you created the issue. So thank you for the issue.

Going forward, the best way to get what you want from a software project you use, or want to use, is to engage in positive conversation with the maintainers, and maybe even contribute to the project. We do this in our spare time, because we love programming. But I don't love it when we disparaging comments. Constructive comments are always welcome.  It's more likely to inspire us to stop working on a project than the other way around. 

If you don't have enough time or know javascript well enough to contribute, that's ok, no one expects you to. But you should also equally respect the fact that you're not paying us to spend our time helping you or provide you with free software. Just be nice. that's all we ask.

**Comment by kokujin** [comment]
I apologize once again. I admit I was a bit rough on you guys. Actually, it was just because I was frustrated for the fact that I have a potentially good tool for my toolbox and I could'nt get it work.

I would, of course, love to help where I can, be it documentation or code. 

Thanks for the code snippet.

**Comment by jonschlinkert** [comment]
help would always be appreciated, thanks
