### ISSUE TITLE
Using with other CLI tools

### ISSUE THREAD

**Issue by jakobrosenberg** [enquirer/enquirer#302]
To speed up installation, I'm running background tasks while using Enquirer to get user input. To keep track of background tasks I'm using Ora, which shows the install status of different packages.

Unfortunately, Ora overwrites the Enquirer prompts. Is there a recommended approach for handling this?

**Comment by jonschlinkert** [comment]
Yes, you need to use the same stream. Instead of using ora, it would be better to use [cli-spinners](https://github.com/sindresorhus/cli-spinners) directly, which is the lib that ora uses. 

Since there is no way to selectively re-render a single character, you'll need to re-render the entire prompt for every "frame". 

Take a look at these examples to get an idea of how you can achieve what you want: 

- https://github.com/enquirer/enquirer/blob/69deef48c8d7535c5175f8b1b981638830541821/examples/select/option-symbols-pointer.js
- https://github.com/enquirer/enquirer/blob/69deef48c8d7535c5175f8b1b981638830541821/examples/fun/heartbeats.js
- https://github.com/enquirer/enquirer/blob/69deef48c8d7535c5175f8b1b981638830541821/examples/fun/multispinner.js

**Comment by jakobrosenberg** [comment]
Thanks!! Impressive response time.
