### ISSUE TITLE
Change default check mark

### ISSUE THREAD

**Issue by 1Map** [enquirer/enquirer#457]
Currently my prompt shows as:

**√** Question · Answer

What I want is for it to display:

**✓** Question · Answer

My code is:

```
import enquirer from 'enquirer'
const somePrompt = new enquirer.StringPrompt({
  name: 'someprompt',
  message: 'Question'
})
somePrompt.run().then(async (answer) => {
  ...
})
```

**Comment by jonschlinkert** [comment]
I believe one or more of [these examples](https://github.com/enquirer/enquirer/tree/master/examples/multiselect) show how to change the symbols on individual choices. 

Closing since I believe this answered in the examples and readme. However, if you want more assistance feel free to start a discussion (which I just enabled!).
